<?php 
if(!defined("DATABASE_HOST")){
define("DATABASE_DRIVER","mysqli");//oci8
define("DATABASE_HOST","db");
define("DATABASE_USER","user");
define("DATABASE_PASSWD","pass");
define("DATABASE_NAME","proyecto");
}
?>